# Generated by Django 3.1.6 on 2021-03-08 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 11, 5, 48, 162043, tzinfo=utc)),
        ),
    ]
