# Generated by Django 3.1.6 on 2021-02-20 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20210218_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 20, 15, 49, 14, 481972, tzinfo=utc)),
        ),
    ]
